name: Build Check
run-name: Build Check
on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'
    # 処理が走るタイミングはプルリク作成時、追加のコミットPush、閉じたプルリクの再開
    types: [opened, synchronize, reopened]
env:
  FILE_PATTERN: "./**/*.{ts,tsx,js,jsx}"
permissions:
  contents: read
jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # リポジトリのコードをチェックアウト

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Node.jsのバージョンを指定

      - name: Build Run
        run: |
          yarn install
          yarn run build

      - name: Report build success
        if: success()
        run: echo "Build completed successfully."

      - name: Report build failure
        if: failure()
        run: echo "Build failed. Please check the logs for details."
